### ISSUE TITLE
一个小小的建议

### ISSUE THREAD

**Issue by xliudaxia** [imxiaoer/DrawerForVue#1]
组件很好用，尤其是对低版本的element，
有个小小的建议，就是右上角的关闭按钮，x，可以替换为
<i class="el-icon-circle-close "></i>
这样会更加美观！

**Comment by icoomn** [comment]
嗯嗯，谢谢你的建议！
之所以特意用的字符 X，是考虑这个组件代码尽量简洁，不想引入图标，或字体图标。
因为大多数项目有自己的图标库， 我这个组件要是再单独引入一个图标文件（或字体库）就显得累赘了，
使用者觉得不好看，自行替换下就行了。
：）
